### ISSUE TITLE
Skip year run after two editons not found (assuming last edition reached)

### ISSUE THREAD

**Issue by uptoratlen** [uptoratlen/gsArchivPDFDownloader#8]
copied from #6 answer
- is it possible to stop the download, when more than 2 pages was not found?

Log file:

```
python gsArchivPDFDownloader.py -y 2021
2021-05-02 12:52:26:[INFO ] gsArchivPDFDownloader Version:0.5.5
2021-05-02 12:52:26:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-05-02 12:52:26:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-05-02 12:52:26:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-05-02 12:52:33:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [xxxxxxxxxxxxxxxxxxx/************************]
2021-05-02 12:52:35:[INFO ] Filename after Download on disk :[GameStar Nr. 1_2021.pdf]
2021-05-02 12:52:35:[INFO ] Filename for Target(modified)   :[GameStar_Nr._01_2021.pdf]
2021-05-02 12:52:35:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2021/GameStar_Nr._01_2021.pdf'
2021-05-02 12:52:35:[INFO ] Filename after Download on disk :[GameStar Nr. 2_2021.pdf]
2021-05-02 12:52:35:[INFO ] Filename for Target(modified)   :[GameStar_Nr._02_2021.pdf]
2021-05-02 12:52:35:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2021/GameStar_Nr._02_2021.pdf'
2021-05-02 12:52:35:[INFO ] Filename after Download on disk :[GameStar Nr. 3_2021.pdf]
2021-05-02 12:52:35:[INFO ] Filename for Target(modified)   :[GameStar_Nr._03_2021.pdf]
2021-05-02 12:52:35:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2021/GameStar_Nr._03_2021.pdf'
2021-05-02 12:52:35:[INFO ] Filename after Download on disk :[GameStar Nr. 4_2021.pdf]
2021-05-02 12:52:35:[INFO ] Filename for Target(modified)   :[GameStar_Nr._04_2021.pdf]
2021-05-02 12:52:35:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2021/GameStar_Nr._04_2021.pdf'
2021-05-02 12:52:35:[INFO ] Filename after Download on disk :[GameStar Nr. 5_2021.pdf]
2021-05-02 12:52:35:[INFO ] Filename for Target(modified)   :[GameStar_Nr._05_2021.pdf]
2021-05-02 12:52:40:[INFO ] Try now download of : Jahr 2021 and Ausgabe 5 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=5
2021-05-02 12:52:52:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:52:54:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:52:55:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:52:57:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:52:58:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:00:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:01:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:03:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:04:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:06:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:07:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:09:[INFO ] C:\Daten\Gamestar-Archive/GameStar Nr. 5_2021.pdf.part Seen- waiting
2021-05-02 12:53:10:[INFO ] Download done successful
2021-05-02 12:53:10:[INFO ] Trying now to move the downloaded file with a timeout of:[30]
2021-05-02 12:53:10:[INFO ] Move Download done successful
2021-05-02 12:53:10:[INFO ] Filename after Download on disk :[GameStar Nr. 6_2021.pdf]
2021-05-02 12:53:10:[INFO ] Filename for Target(modified)   :[GameStar_Nr._06_2021.pdf]
2021-05-02 12:53:15:[INFO ] Try now download of : Jahr 2021 and Ausgabe 6 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=6
2021-05-02 12:53:34:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:53:34:[INFO ] Filename after Download on disk :[GameStar Nr. 7_2021.pdf]
2021-05-02 12:53:34:[INFO ] Filename for Target(modified)   :[GameStar_Nr._07_2021.pdf]
2021-05-02 12:53:39:[INFO ] Try now download of : Jahr 2021 and Ausgabe 7 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=7
2021-05-02 12:53:57:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:53:57:[INFO ] Filename after Download on disk :[GameStar Nr. 8_2021.pdf]
2021-05-02 12:53:57:[INFO ] Filename for Target(modified)   :[GameStar_Nr._08_2021.pdf]
2021-05-02 12:54:02:[INFO ] Try now download of : Jahr 2021 and Ausgabe 8 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=8
2021-05-02 12:54:20:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:54:20:[INFO ] Filename after Download on disk :[GameStar Nr. 9_2021.pdf]
2021-05-02 12:54:20:[INFO ] Filename for Target(modified)   :[GameStar_Nr._09_2021.pdf]
2021-05-02 12:54:25:[INFO ] Try now download of : Jahr 2021 and Ausgabe 9 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=9
2021-05-02 12:54:44:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:54:44:[INFO ] Filename after Download on disk :[GameStar Nr. 10_2021.pdf]
2021-05-02 12:54:44:[INFO ] Filename for Target(modified)   :[GameStar_Nr._10_2021.pdf]
2021-05-02 12:54:49:[INFO ] Try now download of : Jahr 2021 and Ausgabe 10 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=10
2021-05-02 12:55:07:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:55:07:[INFO ] Filename after Download on disk :[GameStar Nr. 11_2021.pdf]
2021-05-02 12:55:07:[INFO ] Filename for Target(modified)   :[GameStar_Nr._11_2021.pdf]
2021-05-02 12:55:12:[INFO ] Try now download of : Jahr 2021 and Ausgabe 11 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=11
2021-05-02 12:55:30:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:55:30:[INFO ] Filename after Download on disk :[GameStar Nr. 12_2021.pdf]
2021-05-02 12:55:30:[INFO ] Filename for Target(modified)   :[GameStar_Nr._12_2021.pdf]
2021-05-02 12:55:35:[INFO ] Try now download of : Jahr 2021 and Ausgabe 12 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=12
2021-05-02 12:55:53:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:55:53:[INFO ] Filename after Download on disk :[GameStar Nr. 13_2021.pdf]
2021-05-02 12:55:53:[INFO ] Filename for Target(modified)   :[GameStar_Nr._13_2021.pdf]
2021-05-02 12:55:58:[INFO ] Try now download of : Jahr 2021 and Ausgabe 13 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2021&bkm=13
2021-05-02 12:56:17:[WARNI] Looks like the page not found is displayed - skip this edition
2021-05-02 12:56:17:[INFO ] Last requested edition downloaded - give job some time (30s) to finish, for no good reason...
2021-05-02 12:56:47:[INFO ] Job done
```
Best regards

_Originally posted by @hightower5 in https://github.com/uptoratlen/gsArchivPDFDownloader/issues/6#issuecomment-830793053_

**Comment by uptoratlen** [comment]
Version 0.5.6 should do the magic. See "abortlimit" in gs.json. But keep an eye also on the new gs_credential.json.
I moved the credentials to a new file. As I may alter the gs.json more often. It will remove the pain from adding the always. I hope that is fine for you. As always tested but with my config and -y 2021.

**Comment by hightower5** [comment]
Hi,

yes I've seen "abortlimit".  ;) There are 4 files in folder 2020 from GameStar_Nr._01_2020 - GameStar_Nr._04_2020. 


python gsArchivPDFDownloader.py -y 2020

```
D:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6>python gsArchivPDFDownloader.py -y 2020
2021-05-04 00:18:48:[INFO ] gsArchivPDFDownloader Version:0.5.6
2021-05-04 00:18:48:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-05-04 00:18:48:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-05-04 00:18:48:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-05-04 00:18:55:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [xxxxxxxxxxxxxxxxxxx/************************]
2021-05-04 00:18:57:[INFO ] Run Type: Year
2021-05-04 00:18:57:[INFO ] Filename after Download on disk :[GameStar Nr. 1_2020.pdf]
2021-05-04 00:18:57:[INFO ] Filename for Target(modified)   :[GameStar_Nr._01_2020.pdf]
2021-05-04 00:18:57:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._01_2020.pdf'
Traceback (most recent call last):
  File "D:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6\gsArchivPDFDownloader.py", line 347, in <module>
    if abortflag >= user_data[0]['abortlimit']:
KeyError: 'abortlimit'
```

There must be a fault. The script didn't download the missing editions from 5 - 12.

**Comment by uptoratlen** [comment]
Could you post the complete gs.json? 
I only get the error if no         "abortlimit": 2, 
is in the gs.json file.
I will add a validator for the gs.json anyway. Maybe it is that easy this time, that  a missing entry caused your error.

**Comment by hightower5** [comment]
My mistake, I was too lazy and have used file comparison to edit gs.json. I have overseen new line "abortlimit": 2. 😆 

OK, but there are still strange lines.

python gsArchivPDFDownloader.py -y 2020

**gs.json:**

```
[
    {
        "log_level": "INFO",
        "downloadtarget": "C:\\Daten\\Gamestar-Archive",
        "edition2d": "Yes",
        "downloadtimeout": 240,
        "abortlimit": 2,
        "filenamepattern_intarget": "GameStar_Nr._<ausgabe>_<jahr>.pdf",
        "filenamepattern_fromserver": "GameStar Nr. <ausgabe>_<jahr>.pdf",
        "latestdownload": [
            {
                "year": "2021",
                "edition": "3"
            }
        ],
        "browser_display_on_latest": "no",
        "editions": [
            {
                "1997": "9,10,11,12"
            },
            {
                "1998": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "1999": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2000": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2001": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2002": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2003": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2004": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2005": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2006": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2007": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2008": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2009": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2010": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2011": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2012": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2013": "1,2,3,4,5,6,7,8,9,10,11,12,13"
            },
            {
                "2014": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2015": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2016": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2017": "1,2,3,4,5,6,7,8,9,11,12"
            },
            {
                "2018": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2019": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2020": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2021": "1,2,3,4"
            }
        ]
    }
]
```

**Log-file:**

```
2021-05-04 11:22:06:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-05-04 11:22:06:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-05-04 11:22:06:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-05-04 11:22:15:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [xxxxxxxxxxxxxxxxxxx/************************]
2021-05-04 11:22:18:[INFO ] Run Type: Year
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 1_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._01_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._01_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 2_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._02_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._02_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 3_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._03_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._03_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 4_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._04_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._04_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 5_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._05_2020.pdf]
2021-05-04 11:22:23:[INFO ] Try now download of : Jahr 2020 and Ausgabe 5 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=5
2021-05-04 11:23:17:[INFO ] Download done successful
2021-05-04 11:23:17:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:23:17:[INFO ] Move Download done successful
2021-05-04 11:23:17:[INFO ] Filename after Download on disk :[GameStar Nr. 6_2020.pdf]
2021-05-04 11:23:17:[INFO ] Filename for Target(modified)   :[GameStar_Nr._06_2020.pdf]
2021-05-04 11:23:22:[INFO ] Try now download of : Jahr 2020 and Ausgabe 6 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=6
2021-05-04 11:23:50:[INFO ] Download done successful
2021-05-04 11:23:50:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:23:50:[INFO ] Move Download done successful
2021-05-04 11:23:50:[INFO ] Filename after Download on disk :[GameStar Nr. 7_2020.pdf]
2021-05-04 11:23:50:[INFO ] Filename for Target(modified)   :[GameStar_Nr._07_2020.pdf]
2021-05-04 11:23:55:[INFO ] Try now download of : Jahr 2020 and Ausgabe 7 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=7
2021-05-04 11:24:23:[INFO ] Download done successful
2021-05-04 11:24:23:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:24:23:[INFO ] Move Download done successful
2021-05-04 11:24:23:[INFO ] Filename after Download on disk :[GameStar Nr. 8_2020.pdf]
2021-05-04 11:24:23:[INFO ] Filename for Target(modified)   :[GameStar_Nr._08_2020.pdf]
2021-05-04 11:24:28:[INFO ] Try now download of : Jahr 2020 and Ausgabe 8 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=8
2021-05-04 11:24:48:[ERROR] Browser page load failed;maybe edition does not exist;or very slow load - timeout exception:Message:
Traceback (most recent call last):
  File "D:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6\gsArchivPDFDownloader.py", line 129, in download_edition
    wait_de.until(ec.visibility_of_element_located((By.XPATH, '//p[@class="title"]')))
  File "C:\Users\Hightower\AppData\local\programs\python\python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

2021-05-04 11:24:48:[INFO ] Filename after Download on disk :[GameStar Nr. 9_2020.pdf]
2021-05-04 11:24:48:[INFO ] Filename for Target(modified)   :[GameStar_Nr._09_2020.pdf]
2021-05-04 11:24:53:[INFO ] Try now download of : Jahr 2020 and Ausgabe 9 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=9
2021-05-04 11:25:20:[INFO ] Download done successful
2021-05-04 11:25:20:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:25:20:[INFO ] Move Download done successful
2021-05-04 11:25:20:[INFO ] Filename after Download on disk :[GameStar Nr. 10_2020.pdf]
2021-05-04 11:25:20:[INFO ] Filename for Target(modified)   :[GameStar_Nr._10_2020.pdf]
2021-05-04 11:25:25:[INFO ] Try now download of : Jahr 2020 and Ausgabe 10 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=10
2021-05-04 11:26:00:[INFO ] Download done successful
2021-05-04 11:26:00:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:26:00:[INFO ] Move Download done successful
2021-05-04 11:26:00:[INFO ] Filename after Download on disk :[GameStar Nr. 11_2020.pdf]
2021-05-04 11:26:00:[INFO ] Filename for Target(modified)   :[GameStar_Nr._11_2020.pdf]
2021-05-04 11:26:05:[INFO ] Try now download of : Jahr 2020 and Ausgabe 11 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=11
2021-05-04 11:26:34:[INFO ] Download done successful
2021-05-04 11:26:34:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:26:34:[INFO ] Move Download done successful
2021-05-04 11:26:34:[INFO ] Filename after Download on disk :[GameStar Nr. 12_2020.pdf]
2021-05-04 11:26:34:[INFO ] Filename for Target(modified)   :[GameStar_Nr._12_2020.pdf]
2021-05-04 11:26:39:[INFO ] Try now download of : Jahr 2020 and Ausgabe 12 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=12
2021-05-04 11:26:59:[ERROR] Browser page load failed;maybe edition does not exist;or very slow load - timeout exception:Message:
Traceback (most recent call last):
  File "D:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6\gsArchivPDFDownloader.py", line 129, in download_edition
    wait_de.until(ec.visibility_of_element_located((By.XPATH, '//p[@class="title"]')))
  File "C:\Users\Hightower\AppData\local\programs\python\python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

2021-05-04 11:26:59:[INFO ] Filename after Download on disk :[GameStar Nr. 13_2020.pdf]
2021-05-04 11:26:59:[INFO ] Filename for Target(modified)   :[GameStar_Nr._13_2020.pdf]
2021-05-04 11:27:04:[INFO ] Try now download of : Jahr 2020 and Ausgabe 13 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=13
2021-05-04 11:27:22:[WARNI] Looks like the page not found is displayed - this edition failed
2021-05-04 11:27:22:[INFO ] As edition was not found; increase abort counter [1/2]
2021-05-04 11:27:22:[INFO ] Last requested edition downloaded - give job some time (30s) to finish, for no good reason...
2021-05-04 11:27:53:[INFO ] Job done
```

**Comment by uptoratlen** [comment]
Ok, that looks like a impact also from the server. I will have a look. 
Maybe I will also add some sort of Update for the gs.son file. Like a new key, that will be added with a default value, so we skip these kind of errors. 
I will check the year 2020 from here (with your config).

**Comment by uptoratlen** [comment]
Could you run again with "-y 2021", this should stop the download at 2021/07 right? 
The year 2020  should be no problem for the abort. As all editions exist.

**Comment by hightower5** [comment]
> I will check the year 2020 from here (with your config). 

Before you start, delete the editions 5 -12 in this folder!

> Could you run again with "-y 2021", this should stop the download at 2021/07 right? 

Correct, the download stopped at 2021/07. 👍

**Comment by uptoratlen** [comment]
for the 2021 test run, thx. This proofs that the new feature "abortlimit" works as expected.
So I will close this one as accepted and move the open question/issue to a new one.
