### ISSUE TITLE
Error while downloading, but continues. Edition not downloaded.

### ISSUE THREAD

**Issue by uptoratlen** [uptoratlen/gsArchivPDFDownloader#9]
OK, but there are still strange lines.

python gsArchivPDFDownloader.py -y 2020

**gs.json:**

```
[
    {
        "log_level": "INFO",
        "downloadtarget": "C:\\Daten\\Gamestar-Archive",
        "edition2d": "Yes",
        "downloadtimeout": 240,
        "abortlimit": 2,
        "filenamepattern_intarget": "GameStar_Nr._<ausgabe>_<jahr>.pdf",
        "filenamepattern_fromserver": "GameStar Nr. <ausgabe>_<jahr>.pdf",
        "latestdownload": [
            {
                "year": "2021",
                "edition": "3"
            }
        ],
        "browser_display_on_latest": "no",
        "editions": [
            {
                "1997": "9,10,11,12"
            },
            {
                "1998": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "1999": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2000": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2001": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2002": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2003": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2004": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2005": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2006": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2007": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2008": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2009": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2010": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2011": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2012": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2013": "1,2,3,4,5,6,7,8,9,10,11,12,13"
            },
            {
                "2014": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2015": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2016": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2017": "1,2,3,4,5,6,7,8,9,11,12"
            },
            {
                "2018": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2019": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2020": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2021": "1,2,3,4"
            }
        ]
    }
]
```

**Log-file:**

```
2021-05-04 11:22:06:[INFO ] Download location:C:\Daten\Gamestar-Archive
2021-05-04 11:22:06:[INFO ] filenamepattern_fromserver:GameStar Nr. <ausgabe>_<jahr>.pdf
2021-05-04 11:22:06:[INFO ] filenamepattern_intarget  :GameStar_Nr._<ausgabe>_<jahr>.pdf
2021-05-04 11:22:15:[INFO ] Browser now started with URL:https://www.gamestar.de/plus/ - try now to log in with user/password [xxxxxxxxxxxxxxxxxxx/************************]
2021-05-04 11:22:18:[INFO ] Run Type: Year
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 1_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._01_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._01_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 2_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._02_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._02_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 3_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._03_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._03_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 4_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._04_2020.pdf]
2021-05-04 11:22:18:[INFO ] Skip download - already existing 'C:\Daten\Gamestar-Archive/2020/GameStar_Nr._04_2020.pdf'
2021-05-04 11:22:18:[INFO ] Filename after Download on disk :[GameStar Nr. 5_2020.pdf]
2021-05-04 11:22:18:[INFO ] Filename for Target(modified)   :[GameStar_Nr._05_2020.pdf]
2021-05-04 11:22:23:[INFO ] Try now download of : Jahr 2020 and Ausgabe 5 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=5
2021-05-04 11:23:17:[INFO ] Download done successful
2021-05-04 11:23:17:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:23:17:[INFO ] Move Download done successful
2021-05-04 11:23:17:[INFO ] Filename after Download on disk :[GameStar Nr. 6_2020.pdf]
2021-05-04 11:23:17:[INFO ] Filename for Target(modified)   :[GameStar_Nr._06_2020.pdf]
2021-05-04 11:23:22:[INFO ] Try now download of : Jahr 2020 and Ausgabe 6 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=6
2021-05-04 11:23:50:[INFO ] Download done successful
2021-05-04 11:23:50:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:23:50:[INFO ] Move Download done successful
2021-05-04 11:23:50:[INFO ] Filename after Download on disk :[GameStar Nr. 7_2020.pdf]
2021-05-04 11:23:50:[INFO ] Filename for Target(modified)   :[GameStar_Nr._07_2020.pdf]
2021-05-04 11:23:55:[INFO ] Try now download of : Jahr 2020 and Ausgabe 7 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=7
2021-05-04 11:24:23:[INFO ] Download done successful
2021-05-04 11:24:23:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:24:23:[INFO ] Move Download done successful
2021-05-04 11:24:23:[INFO ] Filename after Download on disk :[GameStar Nr. 8_2020.pdf]
2021-05-04 11:24:23:[INFO ] Filename for Target(modified)   :[GameStar_Nr._08_2020.pdf]
2021-05-04 11:24:28:[INFO ] Try now download of : Jahr 2020 and Ausgabe 8 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=8
2021-05-04 11:24:48:[ERROR] Browser page load failed;maybe edition does not exist;or very slow load - timeout exception:Message:
Traceback (most recent call last):
  File "D:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6\gsArchivPDFDownloader.py", line 129, in download_edition
    wait_de.until(ec.visibility_of_element_located((By.XPATH, '//p[@class="title"]')))
  File "C:\Users\Hightower\AppData\local\programs\python\python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

2021-05-04 11:24:48:[INFO ] Filename after Download on disk :[GameStar Nr. 9_2020.pdf]
2021-05-04 11:24:48:[INFO ] Filename for Target(modified)   :[GameStar_Nr._09_2020.pdf]
2021-05-04 11:24:53:[INFO ] Try now download of : Jahr 2020 and Ausgabe 9 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=9
2021-05-04 11:25:20:[INFO ] Download done successful
2021-05-04 11:25:20:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:25:20:[INFO ] Move Download done successful
2021-05-04 11:25:20:[INFO ] Filename after Download on disk :[GameStar Nr. 10_2020.pdf]
2021-05-04 11:25:20:[INFO ] Filename for Target(modified)   :[GameStar_Nr._10_2020.pdf]
2021-05-04 11:25:25:[INFO ] Try now download of : Jahr 2020 and Ausgabe 10 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=10
2021-05-04 11:26:00:[INFO ] Download done successful
2021-05-04 11:26:00:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:26:00:[INFO ] Move Download done successful
2021-05-04 11:26:00:[INFO ] Filename after Download on disk :[GameStar Nr. 11_2020.pdf]
2021-05-04 11:26:00:[INFO ] Filename for Target(modified)   :[GameStar_Nr._11_2020.pdf]
2021-05-04 11:26:05:[INFO ] Try now download of : Jahr 2020 and Ausgabe 11 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=11
2021-05-04 11:26:34:[INFO ] Download done successful
2021-05-04 11:26:34:[INFO ] Trying now to move the downloaded file with a _timeout of:[30]
2021-05-04 11:26:34:[INFO ] Move Download done successful
2021-05-04 11:26:34:[INFO ] Filename after Download on disk :[GameStar Nr. 12_2020.pdf]
2021-05-04 11:26:34:[INFO ] Filename for Target(modified)   :[GameStar_Nr._12_2020.pdf]
2021-05-04 11:26:39:[INFO ] Try now download of : Jahr 2020 and Ausgabe 12 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=12
2021-05-04 11:26:59:[ERROR] Browser page load failed;maybe edition does not exist;or very slow load - timeout exception:Message:
Traceback (most recent call last):
  File "D:\Downloads\geckodriver-v0.29.0-win64\gsArchivPDFDownloader-0.6\gsArchivPDFDownloader.py", line 129, in download_edition
    wait_de.until(ec.visibility_of_element_located((By.XPATH, '//p[@class="title"]')))
  File "C:\Users\Hightower\AppData\local\programs\python\python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

2021-05-04 11:26:59:[INFO ] Filename after Download on disk :[GameStar Nr. 13_2020.pdf]
2021-05-04 11:26:59:[INFO ] Filename for Target(modified)   :[GameStar_Nr._13_2020.pdf]
2021-05-04 11:27:04:[INFO ] Try now download of : Jahr 2020 and Ausgabe 13 - URL:https://www.gamestar.de/_misc/plus/showbk.cfm?bky=2020&bkm=13
2021-05-04 11:27:22:[WARNI] Looks like the page not found is displayed - this edition failed
2021-05-04 11:27:22:[INFO ] As edition was not found; increase abort counter [1/2]
2021-05-04 11:27:22:[INFO ] Last requested edition downloaded - give job some time (30s) to finish, for no good reason...
2021-05-04 11:27:53:[INFO ] Job done
```

_Originally posted by @hightower5 in https://github.com/uptoratlen/gsArchivPDFDownloader/issues/8#issuecomment-831817471_

**Comment by uptoratlen** [comment]
I tested the year : no issue here
I also tested your config with same year : no issue seen.

The error seen, is "expected" or let's say could happen. Sometimes I noticed that the server takes a bit longer to display the "save" button. So the edition is displayed but the button is not yet seen. I think there is a 10 seconds grace time. But maybe it needs a bit more.  The log already says:
"Browser page load failed;maybe edition does not exist;or very slow load"

Question: In case you got this run done, with error seen. Could you re-run this? My expectation is that this time it downloads the few missing editions.

Anyway I will check if I could improve this and at least report at the end a list of not downloaded editions (but seen):
like: "Year 2020 done - failed to download editions: [08,12] - try to re-run"
so you get a idea as user what to do next.

**Comment by hightower5** [comment]
**I have made some several tests:**

python gsArchivPDFDownloader.py -y 2020

> Download from 5-12

python gsArchivPDFDownloader.py -l

> Download from  4

python gsArchivPDFDownloader.py -y 2021

> Download from 6-7

python gsArchivPDFDownloader.py

> Download of missing files 

All was fine, no problems any more.

**Comment by uptoratlen** [comment]
Conclusion:
A issue caused by slow server/internet/page load situation.
The proposed log/report will be addressed in a future release (eg. v0.6)
